package lp

object Lista1 extends App {
  // escreva testes de suas funções aqui
  println("Triangulo de pascal")
  println()
  println(pascal(0,0))
  println(pascal(0,1) + " " + pascal(1,1))
  println(pascal(0,2) + " " + pascal(1,2) + " " + pascal(2,2))
  println(pascal(0,3) + " " + pascal(1,3) + " " + pascal(2,3) + " " + pascal(3,3))
  println(pascal(0,4) + " " + pascal(1,4) + " " + pascal(2,4) + " " + pascal(3,4) + " " + pascal(4,4))
  //println(pascal(0,5) + " " + pascal(1,5) + " " + pascal(2,5) + " " + pascal(3,5) + " " + pascal(4,5) + " " + pascal(5,5))
  println()
  println("Parênteses Balanceados")
  println()
  println("Caso de teste 'so (um (teste) (da funcao) )'. Resultado: " + balanceado("so (um (teste) (da funcao) )".toList))
  println("Caso de teste '('. Resultado: " + balanceado("(".toList))
  println("Caso de teste ')'. Resultado: " + balanceado(")".toList))
  println("Caso de teste ')('. Resultado: " + balanceado(")(".toList))
  println("Caso de teste '())('. Resultado: " + balanceado("())(".toList))
  println("Caso de teste '(()((()(())))'. Resultado: " + balanceado("(()((()(())))".toList))
  println("Caso de teste '(()(())((()()))())'. Resultado: " + balanceado("(()(())((()()))())".toList))
  println()
  println("Quicksort")
  println()
  println("Caso de teste 'List(6, 3, 4, 5)'. Resultado: " + quicksort(List(6, 3, 4, 5)))
  println("Caso de teste 'List(6, 7, 4, 5)'. Resultado: " + quicksort(List(6, 7, 4, 5)))
  println("Caso de teste 'List(6)'. Resultado: " + quicksort(List(6)))
  println("Caso de teste 'List()'. Resultado: " + quicksort(List()))
  println()
  println("CR Acumulado")
  println()
  var semestre1 = List((9.0, 5), (8.3, 4), (8.9, 5), (6.7, 4))
  var semestre2 = List((9.0, 5), (5.4, 4), (5.0, 5), (5.3, 4), (10.0, 2), (8.1, 4))
  var semestres = List(semestre1, semestre2)
  println("Semestre 1: " + semestre1)
  println("Semestre 2: " + semestre2)
  println("Resultado: " + crsAcumulados(semestres))
  println()
  semestre1 = List((9.0, 2), (7.2, 4), (7.1, 5), (5.7, 2))
  semestres = List(semestre1)
  println("Semestre 1: " + semestre1)
  println("Resultado: " + crsAcumulados(semestres))
  println()
  semestre2 = List((1.0, 6), (7.0, 1), (2.6, 5), (9.5, 2))
  val semestre3 = List((9.0, 5), (5.4, 4), (5.0, 5), (5.3, 4), (10.0, 2), (8.1, 4))
  semestres = List(semestre1, semestre2, semestre3)
  println("Semestre 1: " + semestre1)
  println("Semestre 2: " + semestre2)
  println("Semestre 3: " + semestre3)
  println(crsAcumulados(semestres))
}
